"""added snippet fields

Revision ID: 04650738aaef
Revises: 25f094d0e074
Create Date: 2021-03-13 07:29:19.460634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04650738aaef'
down_revision = '25f094d0e074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('source', sa.String(length=90), nullable=True))
    op.add_column('snippet', sa.Column('source_type', sa.String(length=60), nullable=True))
    op.drop_column('snippet', 'source_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('source_title', sa.VARCHAR(length=90), nullable=True))
    op.drop_column('snippet', 'source_type')
    op.drop_column('snippet', 'source')
    # ### end Alembic commands ###
