"""Added user to snippet relationship

Revision ID: 25f094d0e074
Revises: 3f0c7312d2da
Create Date: 2021-03-06 07:39:36.147654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f094d0e074'
down_revision = '3f0c7312d2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_dtm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_dtm'), 'user', ['created_dtm'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_title', sa.String(length=90), nullable=True),
    sa.Column('author', sa.String(length=60), nullable=True),
    sa.Column('snippet', sa.String(length=360), nullable=True),
    sa.Column('created_dtm', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_created_dtm'), 'snippet', ['created_dtm'], unique=False)
    op.drop_index('ix_snippets_created_dtm', table_name='snippets')
    op.drop_table('snippets')
    op.drop_index('ix_users_created_dtm', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_dtm', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_index('ix_users_created_dtm', 'users', ['created_dtm'], unique=False)
    op.create_table('snippets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_title', sa.VARCHAR(length=90), nullable=True),
    sa.Column('author', sa.VARCHAR(length=60), nullable=True),
    sa.Column('snippet', sa.VARCHAR(length=360), nullable=True),
    sa.Column('created_dtm', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snippets_created_dtm', 'snippets', ['created_dtm'], unique=False)
    op.drop_index(op.f('ix_snippet_created_dtm'), table_name='snippet')
    op.drop_table('snippet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_dtm'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
