"""Initial DB Migration

Revision ID: f9ef36a83771
Revises: 
Create Date: 2021-03-13 07:42:38.677601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ef36a83771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_dtm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_dtm'), 'user', ['created_dtm'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('snippet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=90), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('author', sa.String(length=60), nullable=True),
    sa.Column('snippet', sa.String(length=360), nullable=True),
    sa.Column('created_dtm', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_created_dtm'), 'snippet', ['created_dtm'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippet_created_dtm'), table_name='snippet')
    op.drop_table('snippet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_dtm'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
